### ISSUE TITLE
book pdf or epub to large for google play due to large images

### ISSUE THREAD

**Issue by nicenemo** [zacharski/pg2dm-python#1]
The book is over 100Mb and therfore can not be uploaded to Google play.
Can the images be cleaned/ reduced to facilate upload?

**Comment by twerp** [comment]
FWIW, I used GhostScript to optimize the filesize down to ~34 MB, using the following command (in Windows, obviously):
`gswin64c.exe -o "%~n1-optimized.pdf" -sDEVICE=pdfwrite -dPDFSETTIINGS=/prepress %1`

Edit: Due to the typo in the above command, GS actually used default settings. Filesize went down to ~52 MB with the intended command:
`gswin64c.exe -o "%~n1-optimized.pdf" -sDEVICE=pdfwrite -dPDFSETTINGS=/prepress %1`
